envName: prod

certificateArn: "arn:aws:acm:eu-west-1:400013494612:certificate/3749608f-9cc1-425b-89f9-54eb6c68f4b1"

dnsHostnames:
  - argocd.guestbookinterview.lol
  - www.guestbookinterview.lol
  - grafana.guestbookinterview.lol

argocd:
  enabled: true
  host: argocd.guestbookinterview.lol

grafana:
  enabled: true
  host: grafana.guestbookinterview.lol
