replicaCount: 2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

pdb:
  minAvailable: 1
  enabled: true

image:
  repository: "400013494612.dkr.ecr.eu-west-1.amazonaws.com/guestbook"
  tag: "966e0fa"

env:
  ENV_NAME: staging
  ENV_COLOR: "#FFC107"   # yellow

ingress:
  host: staging.guestbook.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

externalSecret:
  enabled: true
  remoteSecretName: guestbook/staging/db-secret

resourceQuota:
  hard:
    # Sized for HPA maxReplicas (5 pods):
    # requests: 5 × 100m cpu, 5 × 128Mi memory
    # limits:   5 × 500m cpu, 5 × 512Mi memory
    requests.cpu: "1"
    requests.memory: "700Mi"
    limits.cpu: "3"
    limits.memory: "3Gi"
    pods: "10"
