replicaCount: 2

image:
  repository: "400013494612.dkr.ecr.eu-west-1.amazonaws.com/guestbook"
  tag: "615bd89"

env:
  ENV_NAME: staging
  ENV_COLOR: "#FFC107"   # yellow

ingress:
  host: staging.guestbook.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: false

externalSecret:
  enabled: false
  remoteSecretName: guestbook/staging/db-secret

resourceQuota:
  hard:
    requests.cpu: "1"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
    pods: "10"
